### ISSUE TITLE
ERROR: PHP Warning: current() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by ghost** [marketing-factory/amazon_affiliate#1] opened 2016-07-11 22:11 UTC
There is an error message in the backend of typo3:

> Core: Error handler (FE): PHP Warning: current() expects parameter 1 to be array, null given in /homepages/24/d236653437/htdocs/urbanarchie/cms/typo3conf/ext/amazon_affiliate/Classes/Domain/Model/Product.php line 430

```
    /**
     * @param $amazonProduct
     */
```

...

430: `$fallbackImage = isset($amazonProduct['ImageSets']['ImageSet']['MediumImage']) ? $amazonProduct['ImageSets']['ImageSet'] : current($amazonProduct['ImageSets']['ImageSet']);`

Sorry, but I am not that fine with php. Give me a hint why this error/warning appears.

TYPO3 7.6.9, EXT:amazon_affiliate v.3.0.3

**Comment by sfsmfc** [comment] 2016-08-11 12:29
The problem is, that $amazonProduct['ImageSets']['ImageSet'] is not set and you get no image for the product from amazon. Amazon has updated the output. This is a bug and it should be fixed.

**Comment by sfsmfc** [comment] 2016-08-23 14:24
Problem was fixed

**Closed as completed** 2016-08-23 14:23 UTC
Labels: bug
